from .skill_extraction import SKILL_EXTRACTION_SYSTEM_PROMPT, SKILL_EXTRACTION_USER_PROMPT
from .job_analysis import JOB_ANALYSIS_SYSTEM_PROMPT, JOB_ANALYSIS_USER_PROMPT

__all__ = [
    "SKILL_EXTRACTION_SYSTEM_PROMPT",
    "SKILL_EXTRACTION_USER_PROMPT",
    "JOB_ANALYSIS_SYSTEM_PROMPT",
    "JOB_ANALYSIS_USER_PROMPT",
]
